### ISSUE TITLE
Dataset not available anymore

### ISSUE THREAD

**Issue by yannickfunk** [MareSeestern/VineLeafDisease#3]
Unfortunately, the dataset https://www.kaggle.com/mareseestern/liteleafdisease is not available anymore. Can you post a new, valid link?

Thanks in advance

**Comment by MareSeestern** [comment]
Hi Yanick,
unfortunately, we removed this dataset. We replaced it with a new version of yellow and red autumn color: https://www.kaggle.com/informaticteens/yellow-and-read-autumn-color-grapeleafs

**Comment by yannickfunk** [comment]
Thank you! Could you replace the link in the readme with this link?

**Comment by MareSeestern** [comment]
Sure. We will do it soon. Thanks for the hint.

**Comment by yannickfunk** [comment]
And could you explain where are the labels in the dataset to predict the diseases?

**Comment by MatheLi** [comment]
This repository doesn't fit the new dataset. We will restructure this repository soon.

**Comment by yannickfunk** [comment]
Why is there no "old" dataset anymore? I am interested in this desease predictions, didn't it work out?
